name: C/C++ CI

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Installing Prerequisites 
      run: make prereqs
    - name: Building Virtcomp
      run: make
    - name: Running Tests
      run: make test
